# Generated by Django 5.0.6 on 2024-08-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_amount_to_use_coupo',
            field=models.PositiveBigIntegerField(default=100),
            preserve_default=False,
        ),
    ]
