# Generated by Django 5.0.6 on 2024-08-05 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addresh',
            new_name='address',
        ),
    ]
